# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('total_tickets', models.PositiveIntegerField()),
                ('price_ticket', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('limit_for_tickets', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_tickets', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('voucher_code', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
