# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200107_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remaining_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
