# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_remaining_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
