# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registration_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event_title',
            field=models.CharField(max_length=20),
        ),
    ]
