# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200131_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image',
            field=models.ImageField(upload_to=b'post_images'),
        ),
    ]
