# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200207_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
