# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_organizerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerrequest',
            name='organizer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Organizer'),
            preserve_default=False,
        ),
    ]
