# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_auto_20200211_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='feedback',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
